const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const cursor=$('#demoCursor'), progress=$('#progressBar'), toast=$('#toast');
let runId=0;
const scenarioCopy={
 notes:{label:'NOTES',title:'Keep the important parts of a chat beside the chat.',text:'Watch a useful passage move from ChatGPT into a structured note, get formatted, then split into a sub-page.'},
 prompts:{label:'PROMPTS',title:'Reuse a prompt without breaking your flow.',text:'A saved prompt goes straight into the ChatGPT composer, then the prompt cards are reordered and collapsed.'},
 dashboard:{label:'DASHBOARD',title:'See unfinished work by priority and project.',text:'Filter the conversations that need attention, then reopen the right one instead of hunting through chat history.'},
 search:{label:'SEARCH',title:'Find the right conversation, note or prompt quickly.',text:'Search across Chat Margin, narrow by project, and jump back to the exact work you need.'},
 workspace:{label:'WORKSPACE',title:'Turn the sidebar note into a full working page.',text:'Open the same note in a larger Notion-like workspace while keeping it connected to the ChatGPT conversation.'}
};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function setPanel(name){$$('.cm-tab').forEach(t=>t.classList.toggle('active',t.dataset.panel===name));$$('.cm-view').forEach(v=>v.classList.toggle('active',v.dataset.view===name));}
function pointTo(el,offsetX=.5,offsetY=.5){const stage=$('#appStage').getBoundingClientRect(), r=el.getBoundingClientRect();cursor.style.left=`${r.left-stage.left+r.width*offsetX}px`;cursor.style.top=`${r.top-stage.top+r.height*offsetY}px`;}
async function move(el,ms=620){pointTo(el);await sleep(ms)}
async function click(el){pointTo(el);await sleep(360);cursor.classList.remove('click');void cursor.offsetWidth;cursor.classList.add('click');el.classList.add('demo-click');await sleep(260);el.classList.remove('demo-click')}
function setProgress(v){progress.style.width=`${v}%`}
function updateCopy(name){const c=scenarioCopy[name];$('#stepLabel').textContent=c.label;$('#scenarioTitle').textContent=c.title;$('#scenarioText').textContent=c.text}
function reset(){runId++;const id=runId;setProgress(0);$('#copySource').classList.remove('selected');$('#insertedNote').classList.remove('show','flash');$('#insertedNoteText').innerHTML='';$('#formatToolbar').classList.remove('show');$('#feedbackPageTab').classList.add('hidden');$('.page-tab[data-page="main"]').classList.add('active');$('#feedbackPageTab').classList.remove('active');$('#noteEditor').style.display='block';$('#feedbackPage').style.display='none';$('#composer').classList.remove('has-text');$('#composerText').textContent='';$('#promptA').classList.remove('collapsed');$('#promptB').classList.remove('collapsed','dragging');$('#promptC').classList.add('collapsed');const list=$('#promptList');list.append($('#promptA'),$('#promptB'),$('#promptC'));$$('.dash-card').forEach(c=>c.classList.remove('filtered'));$('#priorityFilter').textContent='All priorities ▾';$('#projectFilter').textContent='All projects ▾';$('#searchInput').value='';$('#searchProject').textContent='All projects ▾';$('#searchResults').innerHTML='<div class="search-empty">Start typing to search across Chat Margin.</div>';$('#workspaceOverlay').classList.remove('open');toast.classList.remove('show');$('#chatTitle').textContent='Website launch plan';$('#cmChatTitle').textContent='Website launch plan';$('#saveStatus').textContent='Just now';return id}
function check(id){return id===runId}
async function typeInto(el,text,speed=24){el.textContent='';for(let i=0;i<text.length;i++){if(!document.body.contains(el))return;el.textContent+=text[i];if(i%3===0)await sleep(speed)}}
async function notesFlow(){const id=reset();setPanel('notes');updateCopy('notes');setProgress(8);await move($('#copySource'));if(!check(id))return;$('#copySource').classList.add('selected');await sleep(900);toast.textContent='Copied from ChatGPT';toast.classList.add('show');setProgress(22);await sleep(650);toast.classList.remove('show');await move($('#noteEditor'));if(!check(id))return;$('#insertedNoteText').textContent='Start with Chrome and Chromium, focus on heavy ChatGPT users, and learn from the first 100 active users before expanding.';$('#insertedNote').classList.add('show','flash');$('#saveStatus').textContent='Saving…';setProgress(42);await sleep(900);$('#insertedNote').classList.remove('flash');$('#saveStatus').textContent='Saved just now';$('#formatToolbar').classList.add('show');await move($('#boldBtn'));await click($('#boldBtn'));if(!check(id))return;$('#insertedNoteText').innerHTML='<strong>Start with Chrome and Chromium</strong>, focus on heavy ChatGPT users, and learn from the first 100 active users before expanding.';setProgress(62);await sleep(800);$('#formatToolbar').classList.remove('show');await move($('#addPage'));await click($('#addPage'));if(!check(id))return;$('#feedbackPageTab').classList.remove('hidden');setProgress(76);await sleep(600);await move($('#feedbackPageTab'));await click($('#feedbackPageTab'));if(!check(id))return;$('.page-tab[data-page="main"]').classList.remove('active');$('#feedbackPageTab').classList.add('active');$('#noteEditor').style.display='none';$('#feedbackPage').style.display='block';setProgress(92);await sleep(1200);await move($('.page-tab[data-page="main"]'));await click($('.page-tab[data-page="main"]'));if(!check(id))return;$('.page-tab[data-page="main"]').classList.add('active');$('#feedbackPageTab').classList.remove('active');$('#noteEditor').style.display='block';$('#feedbackPage').style.display='none';setProgress(100)}
async function promptsFlow(){const id=reset();setPanel('prompts');updateCopy('prompts');setProgress(10);const btn=$('#promptA .send-prompt');await move(btn);await click(btn);if(!check(id))return;const text=btn.dataset.text;$('#composer').classList.add('has-text');setProgress(34);await typeInto($('#composerText'),text,12);if(!check(id))return;await move($('#sendButton'));await sleep(450);setProgress(52);await move($('#dragPromptB'));$('#promptB').classList.add('dragging');await sleep(480);pointTo($('#promptA'),.5,.15);await sleep(700);if(!check(id))return;$('#promptA').before($('#promptB'));$('#promptB').classList.remove('dragging');setProgress(72);await sleep(750);const collapse=$('#promptB .collapse-btn');await move(collapse);await click(collapse);if(!check(id))return;$('#promptB').classList.add('collapsed');collapse.textContent='⌄';setProgress(100)}
async function dashboardFlow(){const id=reset();setPanel('dashboard');updateCopy('dashboard');setProgress(10);await move($('#priorityFilter'));await click($('#priorityFilter'));if(!check(id))return;$('#priorityFilter').textContent='Urgent ▾';$$('.dash-card.medium').forEach(c=>c.classList.add('filtered'));setProgress(38);await sleep(900);await move($('#projectFilter'));await click($('#projectFilter'));if(!check(id))return;$('#projectFilter').textContent='Product launch ▾';$$('.dash-card').forEach(c=>{if(c.dataset.project!=='Product launch')c.classList.add('filtered')});setProgress(68);await sleep(900);const first=$('.dash-card.urgent[data-project="Product launch"]');await move(first);await click(first);if(!check(id))return;$('#chatTitle').textContent='Website launch plan';$('#cmChatTitle').textContent='Website launch plan';first.style.boxShadow='0 0 0 3px rgba(114,97,255,.12)';setProgress(100);await sleep(700);first.style.boxShadow=''}
async function searchFlow(){const id=reset();setPanel('search');updateCopy('search');setProgress(10);await move($('#searchInput'));await click($('#searchInput'));if(!check(id))return;$('#searchInput').value='';for(const ch of 'interview'){if(!check(id))return;$('#searchInput').value+=ch;await sleep(95)}setProgress(35);$('#searchResults').innerHTML='<div class="search-result highlight" id="result1"><strong>User interviews</strong><span>Conversation · Product launch</span><span>…questions from early <em>interviews</em> and activation friction…</span></div><div class="search-result" id="result2"><strong>User feedback</strong><span>Note sub-page · Product launch</span><span>What do users reopen most often after an <em>interview</em>?</span></div><div class="search-result" id="result3"><strong>Interview synthesis</strong><span>Prompt · Research</span><span>Summarize recurring patterns across <em>interview</em> notes.</span></div>';await sleep(800);await move($('#searchProject'));await click($('#searchProject'));if(!check(id))return;$('#searchProject').textContent='Product launch ▾';$('#result3').style.opacity='.18';setProgress(66);await sleep(700);await move($('#result1'));await click($('#result1'));if(!check(id))return;$('#chatTitle').textContent='User interviews';$('#cmChatTitle').textContent='User interviews';setProgress(100)}
async function workspaceFlow(){const id=reset();setPanel('notes');updateCopy('workspace');setProgress(12);await move($('#workspaceBtn'));await click($('#workspaceBtn'));if(!check(id))return;setProgress(42);$('#workspaceOverlay').classList.add('open');await sleep(1100);const nav=$('.workspace-pages button:nth-of-type(2)');await move(nav);await click(nav);if(!check(id))return;$$('.workspace-pages button').forEach(b=>b.classList.remove('active'));nav.classList.add('active');setProgress(75);await sleep(700);await move($('.workspace-doc h2'));setProgress(100)}
const runners={notes:notesFlow,prompts:promptsFlow,dashboard:dashboardFlow,search:searchFlow,workspace:workspaceFlow};
function launch(name){$$('.scenario').forEach(b=>b.classList.toggle('active',b.dataset.scenario===name));updateCopy(name);runners[name]();}
$$('.scenario').forEach(b=>b.addEventListener('click',()=>launch(b.dataset.scenario)));
$$('.cm-tab').forEach(t=>t.addEventListener('click',()=>launch(t.dataset.panel)));
$('#workspaceBtn').addEventListener('click',()=>launch('workspace'));
$('#closeWorkspace').addEventListener('click',()=>{$('#workspaceOverlay').classList.remove('open');launch('notes')});
$$('.send-prompt').forEach(b=>b.addEventListener('click',()=>{const t=b.dataset.text;$('#composer').classList.add('has-text');$('#composerText').textContent=t}));
$$('.collapse-btn').forEach(b=>b.addEventListener('click',()=>{const card=$('#'+b.dataset.card);card.classList.toggle('collapsed');b.textContent=card.classList.contains('collapsed')?'⌄':'⌃'}));
$('#replay').addEventListener('click',()=>{const active=$('.scenario.active');launch(active.dataset.scenario)});
launch('notes');
